[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0.0", features = ["derive"] }
envy = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
