[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
sea-orm-migration = { version = "1.1.14" }
sea-orm = { workspace = true }
tokio = { version = "1.43.0", features = ["full"] }
[[bin]]
name = "migration"
path = "src/main.rs"
