[package]
name = "rest"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.19", features = ["json", "rustls-tls"] }
thiserror = { workspace = true }
tracing = { workspace = true }
