//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::oauth_accounts::Entity as OauthAccounts;
pub use super::user_tokens::Entity as UserTokens;
pub use super::users::Entity as Users;
