//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::feed_records::Entity as FeedRecords;
pub use super::oauth_accounts::Entity as OauthAccounts;
pub use super::pets::Entity as Pets;
pub use super::user_tokens::Entity as UserTokens;
pub use super::users::Entity as Users;
pub use super::work_goals::Entity as WorkGoals;
pub use super::work_records::Entity as WorkRecords;
