//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "login_type")]
pub enum LoginType {
    #[sea_orm(string_value = "Oauth")]
    Oauth,
    #[sea_orm(string_value = "Local")]
    Local,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "provider_type")]
pub enum ProviderType {
    #[sea_orm(string_value = "Google")]
    Google,
    #[sea_orm(string_value = "Meta")]
    Meta,
    #[sea_orm(string_value = "Apple")]
    Apple,
}
